/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Model.db;
import java.awt.image.BufferedImage;
import java.io.File;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {


    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        ResultSet rs=db.search("SELECT * from login where Password="+1234567890+"");
        
    try {
        
        while(rs.next()){
                 String nam=rs.getString("User");
                 String pass=rs.getString("Password");
                 String pic=rs.getString("Pic");
                 String email=rs.getString("Email");
   log.LogBuilder l=new log.LogBuilder(nam, pass);
   l.setPic(pic).setEmail(email).build();
   log u=l.build();
            ImageIcon iop=new ImageIcon(u.getPic());
            image.setIcon(iop);
            nama.setText("User Logged In:  "+u.getUser());
                 
           
        }
        
        //setExtendedState(MAXIMIZED_BOTH);
    } catch (SQLException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(204, 153, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Kids Smiles Drawer");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 180, 110));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Kids Fun Tools");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Change Fun Background 2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 220, 90));

        jButton6.setBackground(new java.awt.Color(255, 0, 51));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Kids Fun Calculator");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, 110));

        image.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        image.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 300, 230));

        nama.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 270, 50));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Change Fun Background 3");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 220, 90));

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Change Fun Background 1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 220, 90));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1020, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       Calypso c=new Calypso();
       c.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
             Caretaker c=new Caretaker();
            Images i=new Images("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\CompoundPatt\\src\\Images\\background.jpg");
            i.saveMemento(c);
            Images ii=new Images("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\CompoundPatt\\src\\Images\\two.jpg");
            ii.saveMemento(c);
            Images iii=new Images("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\CompoundPatt\\src\\Images\\three.jpg");
            iii.saveMemento(c);
            i.restoreMemento(c.getMemento(1));
//           BufferedImage img=ImageIO.read(new File(i.toString()));
            ImageIcon ko=new ImageIcon(i.getImgurl());
          jLabel2.setIcon(ko);
                    
        } catch (Exception e) {
        e.printStackTrace();}     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
Drawer d=new Drawer();
d.setVisible(true);
this.dispose();

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
             Caretaker c=new Caretaker();
        Images i=new Images("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\CompoundPatt\\src\\Images\\background.jpg");
            i.saveMemento(c);
            Images ii=new Images("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\CompoundPatt\\src\\Images\\two.jpg");
            ii.saveMemento(c);
            Images iii=new Images("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\CompoundPatt\\src\\Images\\three.jpg");
            iii.saveMemento(c);
            i.restoreMemento(c.getMemento(2));
            ImageIcon ko=new ImageIcon(i.getImgurl());
          jLabel2.setIcon(ko);
                    
        } catch (Exception e) {
       e.printStackTrace(); }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 try {
             Caretaker c=new Caretaker();
  Images i=new Images("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\CompoundPatt\\src\\Images\\background.jpg");
            i.saveMemento(c);
            Images ii=new Images("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\CompoundPatt\\src\\Images\\two.jpg");
            ii.saveMemento(c);
            Images iii=new Images("C:\\Users\\Lenovo\\Documents\\NetBeansProjects\\CompoundPatt\\src\\Images\\three.jpg");
            iii.saveMemento(c);
            i.restoreMemento(c.getMemento(0));
//            BufferedImage img=ImageIO.read(new File(i.toString()));
            ImageIcon ko=new ImageIcon(i.getImgurl());
          jLabel2.setIcon(ko);
                    
        } catch (Exception e) {
       e.printStackTrace(); }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nama;
    // End of variables declaration//GEN-END:variables

}
