/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.net.URL;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class User extends javax.swing.JFrame {
    
    String imgpath;
public void userstr(){
  String Uid=uid.getText();
    String Uname=uname.getText();
    String Password=uaddress.getText();
    
    
    try {
     
        
      
        Model.db.SUD("insert into login value('"+uid.getText()+"','"+Uname+"','"+imgpath+"','"+Password+"')");
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    
}
    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        
        
    
        
        setdefaultimage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        uimage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        uaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Browse");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        uimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default.png"))); // NOI18N
        getContentPane().add(uimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 130, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("User Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("User Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        uname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                unameKeyPressed(evt);
            }
        });
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 320, -1));

        uaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uaddressKeyPressed(evt);
            }
        });
        getContentPane().add(uaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 320, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        uid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });
        uid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uidKeyPressed(evt);
            }
        });
        getContentPane().add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 320, -1));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 509, 205, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Save & Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 160, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        userstr();
        
        nullmaker();
        JOptionPane.showMessageDialog(this,"Successfully Saved!!!");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void unameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unameKeyPressed
       char c= evt.getKeyChar();
        if(c==evt.VK_ENTER){
            uaddress.grabFocus();
        }
    }//GEN-LAST:event_unameKeyPressed

    private void uaddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uaddressKeyPressed
        char c= evt.getKeyChar();
        if(c==evt.VK_ENTER){
        jButton1.grabFocus();
        }
    }//GEN-LAST:event_uaddressKeyPressed

    private void uidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uidKeyPressed
        char c= evt.getKeyChar();
        if(c==evt.VK_ENTER){
           
           uname.grabFocus();
        }
    }//GEN-LAST:event_uidKeyPressed

    private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       try {
            JFileChooser jf = new JFileChooser();
            int i = jf.showOpenDialog(this);
           
            if (i == jf.APPROVE_OPTION) {
                File f = jf.getSelectedFile();
                String path = f.getAbsolutePath();
               System.out.println(path);
                imgpath = path.replace("\\","/"); 
                f=new File(imgpath);
                Image img=ImageIO.read(f);
                img=img.getScaledInstance(uimage.getWidth(), uimage.getHeight(), img.SCALE_SMOOTH);
                uimage.setIcon(new ImageIcon(img));
                
                
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField uaddress;
    private javax.swing.JTextField uid;
    private javax.swing.JLabel uimage;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
//public void Userini(){
//    String UserNIC=userNIC.getText();
//    String UserName=uname.getText();
//    String UserAddress=uaddress.getText();
//    String UserID=uid.getText();
//    String UserOfficeNo=uoffice.getText();
//    String UserConatct=ucontact.getText();
//    String UserEmail=uemail.getText();
//}

  
    private void nullmaker() {
    
        uid.setText(null);
        uname.setText(null);
        uaddress.setText(null);
     
       
    }

    
   
    private void setdefaultimage() {
    try {
            
       
       URL resource = getClass().getResource("/Images/default.png");
       Image img=ImageIO.read(resource);
       img =img.getScaledInstance(uimage.getWidth(), uimage.getHeight(),Image.SCALE_SMOOTH);
       uimage.setIcon(new ImageIcon(img));
    
        } catch (Exception e) {
            e.printStackTrace();
        }    
    }
    }

